### ISSUE TITLE
problem 4 : problem with input

### ISSUE THREAD

**Issue by RoelofWobben** [PEZ/rich4clojure#4]
On challenge 4 as far as I can see the input is `:a :b: c: `  but I cannot enter it because a def cannot take 3 arguments.

On the calva channel seanconnerfield proposed a solution.

**Comment by RoelofWobben** [comment]
I think the same problem on problem 72

**Comment by PEZ** [comment]
You are not supposed to enter it via the `def`. Just enteer the it in place of `__` in the `tests` form. I've just updated the README to clarify this a bit more.

Keeping this open, because I'm figuring if I can make it clearer still.

**Comment by RoelofWobben** [comment]
oke, is it then not better to delete the def in all those cases till you have figured it out

**Comment by PEZ** [comment]
Without it, the file can't be loaded.
